#!/bin/bash
#
# vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 foldmethod=marker:
#
# 初始化脚本配置文件
#


# 需要启动的进程
ARRAY_START=(
    redis
	rsyslogd
	smond
    cron_etc
)

# 需要停止的进程
ARRAY_STOP=(
    cron_etc
	smond
	rsyslogd
	redis
)

# 需要检查的进程
ARRAY_WATCH=(
	redis "redis-server"
	rsyslogd "rsyslogd"
    cron_etc "crond_etc"
	smond "sw_mond"
)

