#!/bin/sh
# vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4 foldmethod=marker: #
# +---------------------------------------------------------------------------
# | SWAN [ $_SWANBR_SLOGAN_$ ]
# +---------------------------------------------------------------------------
# | Copyright $_SWANBR_COPYRIGHT_$
# +---------------------------------------------------------------------------
# | Version  $_SWANBR_VERSION_$
# +---------------------------------------------------------------------------
# | Licensed ( $_SWANBR_LICENSED_URL_$ )
# +---------------------------------------------------------------------------
# | $_SWANBR_WEB_DOMAIN_$
# +---------------------------------------------------------------------------
#
# swansoft 安装脚本
#
#

# 路径配置
PATH_SWAN="/usr/local/swan_mon"
PATH_OPT="$PATH_SWAN/opt"
PATH_OPT_ETC="$PATH_SWAN/etc"
PATH_APP="$PATH_SWAN/app"
PATH_LOG="$PATH_SWAN/log"
PATH_APP_SBIN="$PATH_APP/sbin"
PATH_PWD=`pwd`
PATH_DATA="$PATH_SWAN/data"
PATH_TMP_INSTALL="$PATH_SWAN/tmp_install"
PATH_TMP_INSTALL_SBIN="$PATH_TMP_INSTALL/sbin"
PATH_TMP_INSTALL_SQL="$PATH_TMP_INSTALL/sql"

# 参数配置
LOG_INSTALL="$PATH_LOG/install.log"
SW_USER="swan"
SW_USER_UID="19389"

# 命令配置
CMD_USERADD="/usr/sbin/useradd"
CMD_USERMOD="/usr/sbin/usermod"
CMD_CHKCONFIG="/sbin/chkconfig"
CMD_SUDO_SWAN="sudo -u swan"

# 高亮输出
ECHO_OK="\033[0;32mOK\033[0m"
ECHO_FAIL="\033[0;31mFAIL\033[0m"
ECHO_NO="\033[0;31mNO\033[0m"


###### 输出信息
echo_log ()
{
    t_echo_argv=""
    t_echo_con=$1
    if [[ $2 ]]; then
        t_echo_argv=$1
        t_echo_con=$2
    fi

    echo $t_echo_argv $t_echo_con >> $LOG_INSTALL 2>&1
    echo $t_echo_argv $t_echo_con
}


###### 输出带有 Build: 前缀的信息
echo_log_prefix ()
{
    t_echo_argv=""
    t_echo_con=$1
    if [[ $2 ]]; then
        t_echo_argv=$1
        t_echo_con=$2
    fi
    t_echo_con="Build: $t_echo_con"

    echo $t_echo_argv $t_echo_con >> $LOG_INSTALL 2>&1
    echo $t_echo_argv $t_echo_con
}


###### 处理日志文件
log_init ()
{
    mkdir -p $PATH_LOG
    touch $LOG_INSTALL
    chmod 777 $LOG_INSTALL
    DATESTR=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "\n\n======== build install $1 $DATESTR ========\n" >> $LOG_INSTALL 2>&1
}


###### 输出手工执行安装脚本的提示
exit_echo_build_manually ()
{
    echo_log_prefix -e "$1. You need exec build_install.sh manually after resolve it. Exit now."
    exit 1
}


###### 检查 swan 用户是否存在
run_check_exec_user ()
{
    t_log_con="check exec as root"
    echo_log_prefix -n "$t_log_con ..."
    if test "root" != `whoami`; then
        echo_log -e "$ECHO_NO"
        exit_echo_build_manually "$t_log_con $ECHO_NO"
    else
        echo_log -e "$ECHO_OK"
    fi

    t_log_con="check user '$SW_USER'"
    echo_log_prefix -n "$t_log_con ..."
    if ! $CMD_USERMOD -e '' $SW_USER >> $LOG_INSTALL 2>&1; then
        echo_log -n "NO, will add it ..."
        if $CMD_USERADD $SW_USER -m -d $PATH_SWAN -u $SW_USER_UID >> $LOG_INSTALL 2>&1; then
            echo_log -e "$ECHO_OK"
        else
            echo_log -e "$ECHO_FAIL"
            exit_echo_build_manually "Add user '$SW_USER' $ECHO_FAIL"
        fi
    else
        echo_log -e "$ECHO_OK"
    fi

    t_log_con="check system can exec sudo cmd"
    echo_log_prefix -n "$t_log_con ..."
    if sudo ls $PATH_SWAN > /dev/null 2>&1; then
        echo_log -e "$ECHO_OK"
    else
        echo_log -e "$ECHO_NO"
        exit_echo_build_manually "$t_log_con $ECHO_NO"
    fi
}

###### 初始化目录结构
run_build_dirs ()
{
    t_log_con="build dirs"
    echo_log_prefix -n "$t_log_con ..."

    $PATH_TMP_INSTALL_SBIN/build_dirs > /dev/null 2>&1

    echo_log -e "$ECHO_OK"
}

###### 设置启动服务脚本
run_set_initd ()
{
    t_log_con="set swan_mon for /etc/init.d/swan_mon and /usr/bin/swan_mon"
    echo_log_prefix -n "$t_log_con ..."

    t_path_swan_soft="$PATH_APP_SBIN/swan_mon"
    t_path_sw_initd="/etc/init.d/swan_mon"
    t_path_sw_usrbin="/usr/bin/swan_mon"
    rm -f $t_path_sw_initd >> $LOG_INSTALL 2>&1
    ln -s $t_path_swan_soft $t_path_sw_initd >> $LOG_INSTALL 2>&1
    rm -f $t_path_sw_usrbin >> $LOG_INSTALL 2>&1
    ln -s $t_path_swan_soft $t_path_sw_usrbin >> $LOG_INSTALL 2>&1
    $CMD_CHKCONFIG swan_mon off >> $LOG_INSTALL 2>&1

    echo_log -e "$ECHO_OK"
}


###### start
log_init "start"


##### run
run_check_exec_user
run_build_dirs
run_set_initd

###### finish
log_init "finish"

